find_package(PkgConfig)
pkg_check_modules(PC_LIBPLISTPP QUIET plist++)

find_path(LIBPLISTPP_INCLUDE_DIR
        NAMES plist/plist++.h
        HINTS ${PC_LIBPLISTPP_INCLUDEDIR} ${PC_LIBPLISTPP_INCLUDE_DIRS})
find_library(LIBPLISTPP_LIBRARY
        NAMES plist++ libplist++
        HINTS ${PC_LIBPLISTPP_LIBDIR} ${PC_LIBPLISTPP_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBPLISTPP DEFAULT_MSG
        LIBPLISTPP_LIBRARY LIBPLISTPP_INCLUDE_DIR)

mark_as_advanced(LIBPLISTPP_INCLUDE_DIR LIBPLISTPP_LIBRARY)

set(LIBPLISTPP_LIBRARIES ${LIBPLISTPP_LIBRARY})
set(LIBPLISTPP_INCLUDE_DIRS ${LIBPLISTPP_INCLUDE_DIR})